# Site settings
title: "Cultivator - return on behaviour"
email: "ch@cultivator.com"
description: > # this means to ignore newlines until "baseurl:"
  Cultivator hjælper din virksomhed videre - din samarbejdspartner med fokus på indlevelse, mod og erfaring.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cultivator.com" # the base hostname & protocol for your site
twitter_username: recph
github_username:  re-cph

# Build settings
markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']